build: false  # Tell appveyor to not use msbuild

environment:
  matrix:
    - PYTHON: 2.7

platform:
  - x86
  - x64

init:
  - "ECHO %PYTHON%"
  - ps: Start-FileDownload 'http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi' C:\VCForPython27.msi; echo "Done"
  - cmd: msiexec /i C:\VCForPython27.msi /quiet /qn

install:
  # Miniconda setup + necessary external packages
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%  # miniconda is already installed on appveyor: https://github.com/appveyor/ci/issues/359
  - conda update conda --yes
  # - conda update --all --yes
  - conda info -a
  - conda install --yes bitarray cython ipython matplotlib mock nose numba numpy pyserial pytables pyyaml pyzmq scipy sphinx
  - conda install --yes pywin32
  - pip install progressbar-latest pyvisa pyvisa-py
  # - pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop
  - pip install git+https://github.com/SiLab-Bonn/pyqtgraph.git@develop # keeping this fork until release 0.9.11
  - pip install git+https://github.com/uvemas/ViTables@v2.1
  # test packages required for USB interface
  - pip install pyusb
  - pip install pySiLibUSB
  # pyBAR installation including additional specific packages
  - pip install basil_daq==2.4.3
  # - pip install pyBAR_fei4_interpreter
  - pip install git+https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter@1.2.1
  - pip install pixel_clusterizer==2.5.0
  - python.exe setup.py develop
  - conda list
  - pip list

test_script:
  - cd pybar/testing
  - nosetests test_analysis.py
